/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.proyecto2.view;

import edd.proyecto2.files.GenerateFile;
import edd.proyecto2.model.LocalData;
import edd.proyecto2.model.Peer;
import edd.proyecto2.network.Blockchain;
import edd.proyecto2.network.ServerThread;
import edd.proyecto2.node.NodeCategory;
import edd.proyecto2.structure.AVLTreeCategory;
import edd.proyecto2.structure.SimplyLinkedListPeer;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar
 */
public class UserDashboard extends javax.swing.JFrame {
    
    private Blockchain blockchain;
    /**
     * Creates new form UserDashboard
     */
    
    public UserDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        LocalData.currentWindow = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bibliotecaBtn = new javax.swing.JButton();
        bibliotecaVirtualBtn = new javax.swing.JButton();
        editarPerfilBtn = new javax.swing.JButton();
        cerrarSesionBtn = new javax.swing.JButton();
        conexionRemotaBtn = new javax.swing.JButton();
        reporteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bibliotecaBtn.setText("Mi Biblioteca");
        bibliotecaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaBtnActionPerformed(evt);
            }
        });

        bibliotecaVirtualBtn.setText("Conectarse a biblioteca virtual");
        bibliotecaVirtualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bibliotecaVirtualBtnActionPerformed(evt);
            }
        });

        editarPerfilBtn.setText("Editar perfil");
        editarPerfilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarPerfilBtnActionPerformed(evt);
            }
        });

        cerrarSesionBtn.setText("Cerrar sesion");
        cerrarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBtnActionPerformed(evt);
            }
        });

        conexionRemotaBtn.setText("Configuracion de conexion remota");
        conexionRemotaBtn.setActionCommand("");
        conexionRemotaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conexionRemotaBtnActionPerformed(evt);
            }
        });

        reporteBtn.setText("Reportes");
        reporteBtn.setToolTipText("");
        reporteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bibliotecaVirtualBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(conexionRemotaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addComponent(bibliotecaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarPerfilBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bibliotecaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bibliotecaVirtualBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(conexionRemotaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarPerfilBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBtnActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_cerrarSesionBtnActionPerformed

    private void editarPerfilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPerfilBtnActionPerformed
        this.dispose();
        UserProfile userProfile = new UserProfile();
        userProfile.setVisible(true);
    }//GEN-LAST:event_editarPerfilBtnActionPerformed

    private void bibliotecaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaBtnActionPerformed
        this.dispose();
        LibraryDashboard libraryDashboard = new LibraryDashboard();
        libraryDashboard.setVisible(true);
    }//GEN-LAST:event_bibliotecaBtnActionPerformed

    private void reporteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteBtnActionPerformed
        this.dispose();
        ReportDashboard reports = new ReportDashboard();
        reports.setVisible(true);
    }//GEN-LAST:event_reporteBtnActionPerformed

    private void conexionRemotaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conexionRemotaBtnActionPerformed
        this.dispose();
        RemoteConfiguration remote = new RemoteConfiguration();
        remote.setVisible(true);
    }//GEN-LAST:event_conexionRemotaBtnActionPerformed
    private void syncLocalData(){
        LocalData.virtualLibrary = new AVLTreeCategory();
        LocalData.currentUser.getCategories().getAll(LocalData.currentUser.getRoot()).stream().filter((c) -> (c!=null)).forEach((c) -> {
            
            LocalData.virtualRoot = LocalData.virtualLibrary.insert( LocalData.virtualRoot, c);
            LocalData.virtualLibrary.syncRoot(LocalData.virtualRoot);
        });
    }
    private void bibliotecaVirtualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bibliotecaVirtualBtnActionPerformed

        if(LocalData.remote !=null){
            this.dispose();
            VirtualLibraryDashboard virtualLibrary = new VirtualLibraryDashboard();
            virtualLibrary.setVisible(true);
            ServerThread serverThread = new ServerThread(LocalData.remote.getPort());
            serverThread.start();
            syncLocalData();
            blockchain = new Blockchain();
            blockchain.sync();
            blockchain.registerPeer();
        }else{
            JOptionPane.showMessageDialog(this, "Debe configurar un puerto y una ip", "Error de conexion", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_bibliotecaVirtualBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new UserDashboard().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bibliotecaBtn;
    private javax.swing.JButton bibliotecaVirtualBtn;
    private javax.swing.JButton cerrarSesionBtn;
    private javax.swing.JButton conexionRemotaBtn;
    private javax.swing.JButton editarPerfilBtn;
    private javax.swing.JButton reporteBtn;
    // End of variables declaration//GEN-END:variables
}
