/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd.proyecto2.view;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import edd.proyecto2.files.GenerateFile;
import edd.proyecto2.model.Block;
import edd.proyecto2.model.LocalData;
import edd.proyecto2.network.ServerThread;
import edd.proyecto2.node.NodeBlock;
import edd.proyecto2.structure.DoubleLinkedListBlock;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Omar
 */
public class VirtualLibraryDashboard extends javax.swing.JFrame {
    
    private GenerateFile generate;
    private Gson gson;
    /**
     * Creates new form VirtualLibraryDashboard
     */
    public VirtualLibraryDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        LocalData.currentWindow = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libraryBtn = new javax.swing.JButton();
        generarBloqueBtn = new javax.swing.JButton();
        cerrarConexionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        libraryBtn.setText("Biblioteca");
        libraryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryBtnActionPerformed(evt);
            }
        });

        generarBloqueBtn.setText("Generar bloque");
        generarBloqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBloqueBtnActionPerformed(evt);
            }
        });

        cerrarConexionBtn.setText("Cerrar conexion");
        cerrarConexionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarConexionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrarConexionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(generarBloqueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(libraryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(libraryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(generarBloqueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrarConexionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void libraryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryBtnActionPerformed
        LocalData.localEdit = false;
        this.dispose();
        LibraryDashboard libraryDashboard = new LibraryDashboard();
        libraryDashboard.setVisible(true);
    }//GEN-LAST:event_libraryBtnActionPerformed

    private void cerrarConexionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarConexionBtnActionPerformed
        ServerThread.closeConnection();
        deletePeers();
        this.dispose();
        UserDashboard userDashboard = new UserDashboard();
        userDashboard.setVisible(true);
        LocalData.localEdit=true;
    }//GEN-LAST:event_cerrarConexionBtnActionPerformed
    private void generateChain(){
        generate = new GenerateFile();
        List<Block> chain = new ArrayList();
        GsonBuilder gsonBuilder = new GsonBuilder();
        gsonBuilder.setPrettyPrinting();
        gson = gsonBuilder.create();
        String fileChainString;
        NodeBlock aux = LocalData.blockchain.first;
        while(aux!=null){
            if(aux.getInfo()!=null){
                chain.add(aux.getInfo());
            }
            aux = aux.getNext();
        }
        fileChainString = gson.toJson(chain);
        generate.writeFile("chain.json", fileChainString);
    }
            
    private void generarBloqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBloqueBtnActionPerformed
        Block block = null;
        if(!LocalData.operations.isEmpty()){
             if(LocalData.blockchain==null){
                LocalData.blockchain = new DoubleLinkedListBlock();
                block = new Block(LocalData.operations,0000);
                LocalData.blockchain.addToFinal(block);
            }else{
                block = new Block(LocalData.operations, LocalData.blockchain.getLastIndex());
                LocalData.blockchain.addToFinal(block);
            }
            JOptionPane.showMessageDialog(this, "Bloque generado correctamente", "Bloque generado", JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(LocalData.blockchain!=null){
            LocalData.blockchain = new DoubleLinkedListBlock();
            block = new Block(0000);
            LocalData.blockchain.addToFinal(block);
            }else{
                block = new Block(LocalData.blockchain.getLastIndex());
                LocalData.blockchain.addToFinal(block);
            }
            LocalData.currentBlock = block;
            JOptionPane.showMessageDialog(this, "Bloque generado correctamente", "Bloque generado", JOptionPane.INFORMATION_MESSAGE);
            }
        generateChain();
    }//GEN-LAST:event_generarBloqueBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        LocalData.localEdit=false;
    }//GEN-LAST:event_formWindowClosing
    
    private void deletePeers(){
        File file = new File(GenerateFile.getTemp() + "Peers.json");
        if(file.exists()){
            file.delete();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirtualLibraryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirtualLibraryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirtualLibraryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirtualLibraryDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirtualLibraryDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarConexionBtn;
    private javax.swing.JButton generarBloqueBtn;
    private javax.swing.JButton libraryBtn;
    // End of variables declaration//GEN-END:variables
}
